#!/bin/bash

################################################################################
# Copyright (c) 2020 ModalAI, Inc. All rights reserved.
#
# author: james@modalai.com
################################################################################



systemctl daemon-reload

echo ""
echo "Done installing voxl-open-vins-server"
echo ""