#!/bin/sh
################################################################################
# Copyright (c) 2022 ModalAI, Inc. All rights reserved.
#
# author: james@modalai.com
################################################################################

# try to reload services, but don't fail if it can't
set +e
if [ -f /bin/systemctl ]; then
	systemctl daemon-reload
fi

## always exit 0 to keep opkg happy in voxl-emulator
exit 0
