#!/bin/sh
################################################################################
# Copyright (c) 2022 ModalAI, Inc. All rights reserved.
#
# author: james@modalai.com
################################################################################

set -e

# try to reload services, but don't fail if it can't
ldconfig

# make sure there is a newline at the end here or opkg will whine
