/**
 * THIS A BACKUP CONFIG FILE FOR TESTS AT STARLING_FIRST_FLIGHTS TAG
 * 2/8/23 matt
 *
 *
 * expects a front and rear ov9782 with the extensions specified
 * the main important params here are:
 * grid dims and window size for lk
 *
 *
 *
 * This file contains configuration that's specific to voxl-feature-tracker.
 *
 * Per camera, need:
 * cami_enable: en or disable cam
 * cami_name: pipe name
 * cami_mode: MONO, STEREO, STEREO_LEFT_ONLY, STEREO_RIGHT_ONLY
 * cami_extrinsics_extension_first: if extrinsics file uses a suffix, add here
 * cami_extrinsics_extension_second: same as above but only applies to stereo pairs
 *
 * For the tracker, need:
 * num_features_to_track: n per cam
 * en_gyro: enable gyro based predictions
 * imu_name: only needed if en_gyro
 * en_descriptors: enable descriptor calcs
 * grid_x: grid dimensions in x direction
 * grid_y: grid dimensions in y direction
 * min_pix_dist: minimum pixel distance between feature points
 * pyramid_levels: levels for img pyramid (how many layers to track across)
 * window_size: will be the same for x and y, search window for flow calcs
 * en_database: whether or not to store keyframes in a db for mid term lookups
 * database_size: number of frames our db can store
 * max_angular_rate_before_blur: max allowed angular rate around exposure period
 * of frame for it to be used, otherwise discarded. Set negative to disable/ignore
 *
 */
{
	"cam0_enable":	1,
	"cam0_name":	"stereo",
	"cam0_mode":	"STEREO",
	"cam0_extrinsics_extension_first":	"_front_upper",
	"cam0_extrinsics_extension_second":	"_front_lower",
	"cam1_enable":	0,
	"cam1_name":	"flir",
	"cam1_mode":	"MONO",
	"cam1_extrinsics_extension_first":	"0_raw",
	"cam1_extrinsics_extension_second":	"",
	"cam2_enable":	0,
	"cam2_name":	"flir0_raw",
	"cam2_mode":	"MONO",
	"cam2_extrinsics_extension_first":	"",
	"cam2_extrinsics_extension_second":	"",
	"cam3_enable":	0,
	"cam3_name":	"",
	"cam3_mode":	"",
	"cam3_extrinsics_extension_first":	"",
	"cam3_extrinsics_extension_second":	"",
	"imu_name":	"imu_apps",
	"num_features_to_track":	30,
	"grid_x":	10,
	"grid_y":	10,
	"min_pix_dist":	2,
	"pyramid_levels":	2,
	"window_size":	20,
	"fast_threshold":	15,
	"en_gyro":	true,
	"en_descriptors":	false,
	"en_database":	false,
	"database_size":	30,
	"max_angular_rate_before_blur":	-1
}
