#!/bin/bash

# Initialize global variables
directory_path="/data/modalai"
camera_key_name="tracking"
make_intrinsics=1

# Function to check if the specified directory exists and change to it
change_to_directory() {
    local dir=$1
    if [ ! -d "$dir" ]; then
        echo "Directory not found: $dir" >&2
        exit 1
    fi
    cd "$dir" || exit 1
}

# Function to check for the existence of calibration files and set variables
check_calibration_files() {
    local file_paths=("$directory_path/opencv_tracking_intrinsics.yml" "$directory_path/opencv_tracking_grey_intrinsics.yml")
    local keys=("tracking" "tracking_grey")
    local i=0

    for path in "${file_paths[@]}"; do
        if [ -f "$path" ]; then
            make_intrinsics=0
            camera_key_name="${keys[i]}"
            [ "$camera_key_name" == "tracking_grey" ] && is_color=1
            break
        fi
        ((i++))
    done
}

# Function to prompt user to select two files
prompt_for_file_selection() {
    echo "Searching for cam cals in $directory_path... I found this--"
    local file1=$(select_file "Select #1 file:")
    local file2=$(select_file "Select #2 file:")
    echo "You selected: $file1 and $file2"
    echo ""
    process_files "$file1" "$file2"
}

# Function to list files and let the user select one
select_file() {
    local prompt=$1
    echo "$prompt"
    local files=(*.yml)
    select file in "${files[@]}"; do
        if [[ -n $file ]]; then
            echo "$file"
            break
        else
            echo "Invalid selection. Please try again."
        fi
    done
}

# Function to process the selected files and generate a new calibration file
process_files() {
    local file1=$1
    local file2=$2
    choose_camera_type
    local dest="$directory_path/$camera_key_name.yml"

    echo "Combining $file1 and $file2 into $dest"
    # Insert file processing here...
}

# Function to let the user choose the camera type
choose_camera_type() {
    echo "What type of tracking cameras do you have:"
    local options=("tracking" "tracking_grey" "skip")
    select opt in "${options[@]}"; do
        case $REPLY in
            1|2) camera_key_name=${options[$REPLY-1]}; break ;;
            3) echo "Skipping configuration"; exit 0 ;;
            *) echo "Invalid choice. Please try again." ;;
        esac
    done
}

# Redirect stdout to the terminal
exec 3>&1 1>/dev/tty

# Main execution starts here
echo "The following will require you to select 2 INDEPENDENT camera calibration files"
echo "What is generated is a combined file for OVINS use"
echo "See doc.modalai.com for further details"
echo ""

change_to_directory "$directory_path"
check_calibration_files

if [ $make_intrinsics -eq 1 ]; then
    prompt_for_file_selection
else
    echo "Calibration files already exist. Using $camera_key_name configuration."
    # Proceed with existing files or other operations...
fi

echo "Done."
