#!/bin/bash

exec 3>&1 1>/dev/tty

echo "The following will require you to select 2 INDEPENDENT camera calibration files"
echo "What is generated is a combined file for OVINS use"
echo "See doc.modalai.com for further details"
echo ""

# unit test
# Prompt user to select a directory
#echo "Please enter the directory path:"
#read -r directory_path

# unit test
#directory_path="."

directory_path="/data/modalai"

# Check if the directory exists
if [ ! -d "$directory_path" ]; then
    echo "Directory not found: $directory_path"
    exit 1
fi

# Change to the specified directory
cd "$directory_path" || exit 1

make_intrinsics=1
camera_key_name="tracking"
    
#if [ -f "$directory_path/opencv_stereo_front_intrinsics.yml" ]; then
#    make_intrinsics=0
#    camera_key_name="tracking_grey"
#    is_color=1
#fi     
    
if [ -f "$directory_path/opencv_tracking_intrinsics.yml" ]; then
    make_intrinsics=0
    camera_key_name="tracking"
fi 
if [ -f "$directory_path/opencv_tracking_grey_intrinsics.yml" ]; then
    make_intrinsics=0
    camera_key_name="tracking_grey"
    is_color=1
fi 

if [ $make_intrinsics -eq 1 ]; then
    # List files in the directory
    files=(*.yml)

    # Prompt user to select 2 files
    echo "Searching for cam cals in /data/modalai... I found this--"
    echo "Select #1 file:"
    select file1 in "${files[@]}"; do
        [[ -n $file1 ]] && break
        echo "Invalid selection. Please try again."
    done
    
    echo "Select #2 file:"
    select file2 in "${files[@]}"; do
        [[ -n $file2 ]] && break
        echo "Invalid selection. Please try again."
    done


    echo "What type of tracking cameras do you have:"
    echo "1) tracking (most cameras)"
    echo "2) tracking_grey (color mode ov92xx)"
    echo "3) I've already did this, skip"
    echo " "
    read choice

    case $choice in
        1)
            dest="$directory_path/opencv_tracking_intrinsics.yml"
            camera_key_name="tracking"

            ;;
        2)
            dest="$directory_path/opencv_tracking_grey_intrinsics.yml"
            camera_key_name="tracking_grey"

            ;;
        3)
	    echo "ok, continuing..."
            sed -i $sed_key "/etc/modalai/voxl-camera-server.conf"
            exit 0
            ;;
        *)
            echo "Invalid choice. Exiting."
            exit 1
            ;;
    esac

    echo "You selected:" 
    echo " " 
    echo "$file1 and $file2"
    echo "to be made into configuration:"
    echo " " 
    echo "$dest"

    echo " " 
    echo "CTRL-C to exit. Otherwise press <ENTER> to create new config."

    read enter

    # unit test
    ## Check if the correct number of arguments is provided
    #if [ "$#" -ne 3 ]; then
    #    echo "Usage: $0 source_file1 source_file2 destination_file"
    #    exit 1
    #fi
    
    # Set source and destination files
    source_file1=$file1
    source_file2=$file2
    destination_file=$dest

    cp "$source_file1" "$source_file1"_tmp
    cp "$source_file2" "$source_file2"_tmp

    # Use sed to replace "M:" with "M1:"
    sed -i 's/M:/M1:/g' "$source_file1"_tmp
    sed -i 's/D:/D1:/g' "$source_file1"_tmp
    sed -i 's/reprojection_error:/reprojection_error1:/g' "$source_file1"_tmp
    sed -i 's/M:/M2:/g' "$source_file2"_tmp
    sed -i 's/D:/D2:/g' "$source_file2"_tmp
    sed -i 's/reprojection_error:/reprojection_error2:/g' "$source_file2"_tmp


    # Use sed to extract lines 3 to 15 from the source file and insert them into the destination file at line 3
    sed -n '3,15p' "$source_file1"_tmp | sed '2r /dev/stdin' "$source_file2"_tmp > temp_file && mv temp_file "$destination_file"

    rm "$source_file1"_tmp "$source_file2"_tmp
fi

rm -f /etc/modalai/voxl-feature-tracker.conf

if [ "$camera_key_name" == "tracking_grey" ]; then
    echo ""
    echo "COLOR"
    echo ""
    voxl-open-vins-server --config 1
else
    echo ""
    echo "MONOCHROME"
    echo ""
    voxl-open-vins-server --config 0
fi

sed_key="s/stereo/$camera_key_name/g"
sed -i $sed_key "/etc/modalai/voxl-camera-server.conf"
sed -i 's/GPS=AUTO/GPS=NONE/g' "/etc/modalai/voxl-px4.conf"
sed -i 's/auto/performance/g' "/etc/modalai/voxl-cpu-monitor.conf"

echo "Done."
