#!/bin/bash
################################################################################
# Copyright 2022 ModalAI Inc.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# 4. The Software is used solely in conjunction with devices provided by
#    ModalAI Inc.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
################################################################################

NAME="voxl-open-vins-server"
SERVICE_FILE="${NAME}.service"
CONFIG_FILE="/etc/modalai/${NAME}.conf"
USER=$(whoami)


print_usage () {
	echo ""
	echo "voxl-configure-open-vins disable"
	echo "voxl-configure-open-vins factory_enable"
	echo "voxl-configure-open-vins enable"
	echo "voxl-configure-open-vins starling_v2 (ov72)" 
	echo "voxl-configure-open-vins starling_v2.5 (ov97 mono)"
	echo "voxl-configure-open-vins starling_v2.7 (ov97 color)"
	echo "voxl-configure-open-vins px4 (ar144)"
	echo "voxl-configure-open-vins fpv (ov97 color)"
	echo "voxl-configure-open-vins manual (uses existing extrinsics & intrinsics)"
	echo "voxl-configure-open-vins prep (cleans data area for reconfig)"
	echo ""
	echo "show this help message:"
	echo "voxl-configure-open-vins help"
	echo ""
	exit 0
}


## set most parameters which don't have quotes in json
set_param () {
	if [ "$#" != "2" ]; then
		echo "set_param expected 2 args"
		exit 1
	fi

	# remove quotes if they exist
	var=$1
	var="${var%\"}"
	var="${var#\"}"
	val=$2
	val="${val%\"}"
	val="${val#\"}"

	sed -E -i "/\"$var\":/c\	\"$var\":	$val," ${CONFIG_FILE}
}

## set string parameters which need quotes in json
set_param_string () {
	if [ "$#" != "2" ]; then
		echo "set_param_string expected 2 args"
		exit 1
	fi
	var=$1
	var="${var%\"}"
	var="${var#\"}"
	sed -E -i "/\"$var\":/c\	\"$var\":	\"$2\"," ${CONFIG_FILE}
}


disable_service_and_exit () {
	echo "disabling ${NAME} systemd service"
	systemctl disable ${SERVICE_FILE}
	echo "stopping ${NAME} systemd service"
	systemctl stop ${SERVICE_FILE}
	echo "Done configuring ${NAME}"
	exit 0
}

enable_service_and_exit () {
	echo "enabling  ${NAME} systemd service"
	systemctl enable  ${SERVICE_FILE}
	echo "Please recycle power to reflect changes"
	echo "Done configuring ${NAME}"
	exit 0
}

reset_config_file_to_default () {
	echo "wiping old config file"
	rm -rf ${CONFIG_FILE}
	${NAME} -c
}


################################################################################
## actual start of execution, handle optional arguments first
################################################################################

## sanity checks
if [ "${USER}" != "root" ]; then
	echo "Please run this script as root"
	exit 1
fi

## convert argument to lower case for robustness
arg=$(echo "$1" | tr '[:upper:]' '[:lower:]')

## parse arguments
case ${arg} in
	""|"h"|"-h"|"help"|"--help")
		print_usage
		exit 0
		;;
	"disable")
		disable_service_and_exit
		;;
	"factory_enable")
		reset_config_file_to_default
		enable_service_and_exit
		;;
	"enable")
		enable_service_and_exit
		;;
	"starling_v2.5")
		reset_config_file_to_default
		new_dual_config
		#voxl-open-vins-server --config 0
		cp "/data/modalai/ov/ext/extrinsics.conf_ov97_mono_up_down" "/etc/modalai/extrinsics.conf"
		
		enable_service_and_exit
		;;		
	"starling_v2.7")
		reset_config_file_to_default
		new_dual_config
		#voxl-open-vins-server --config 0
		cp "/data/modalai/ov/ext/extrinsics.conf_ov97_up_down" "/etc/modalai/extrinsics.conf"
		
		enable_service_and_exit
		;;
	"starling_v2")
		reset_config_file_to_default
		new_dual_config
		#voxl-open-vins-server --config 0
		cp "/usr/share/modalai/extrinsic_configs/starling_v2_voxl2.conf" "/etc/modalai/extrinsics.conf"
		
		sed -i 's/tracking/tracking_front/g' "/etc/modalai/extrinsics.conf"
		enable_service_and_exit
		;;
	"px4")
		reset_config_file_to_default
		new_dual_config
		#voxl-open-vins-server --config 0
		cp "/usr/share/modalai/extrinsic_configs/d0011_starling_px4_edition.conf" "/etc/modalai/extrinsics.conf"
		
		enable_service_and_exit
		;;
	"fpv")
		reset_config_file_to_default
		new_dual_config
		#voxl-open-vins-server --config 0
		cp "/usr/share/modalai/extrinsic_configs/fpv_revB.conf" "/etc/modalai/extrinsics.conf"
		sed -i 's/trackingL/tracking_grey_front/g' "/etc/modalai/extrinsics.conf"
		
		enable_service_and_exit
		;;
	"manual")
		reset_config_file_to_default
		new_dual_config
		enable_service_and_exit
		exit 0
		;;
	"prep")
		mv /data/modalai/opencv_tracking_grey_intrinsics.yml /data/modalai/opencv_tracking_grey_intrinsics.yml.1
#		mv /data/modalai/opencv_tracking_intrinsics.yml /data/modalai/opencv_tracking_grey_intrinsics.yml.1
		exit 0
		;;
		
		
	*)
		echo "invalid option"
		print_usage
		exit 1
esac



################################################################################
## no optional arguments, start config wizard prompts
################################################################################

echo " "
echo "Do you want to reset the config file to factory defaults?"
select opt in "yes" "no"; do
case $opt in
yes )
	reset_config_file_to_default
	break;;
no )
	echo "loading and updating config file with ${NAME} -c"
	${NAME} -c
	break;;
*)
	echo "invalid option"
	esac
done


# ask if the user wants the service enabled or not
echo " "
echo "Do you want to enable the voxl-open-vins-server service to allow"
echo "visual inertial odometry?"
select opt in "yes" "no"; do
case $opt in
yes )
	echo " "
	echo "Now we are going to do a preliminary configuration of ${CONFIG_FILE}"
	break;;
no )
	disable_service_and_exit
	break;;
*)
	echo "invalid option"
	esac
done


# all done!
enable_service_and_exit

