/**
 * This file contains configuration that's specific to voxl-open-vins-server.
 * 
 * *NOTE*: all time variables are measured in seconds
 */
{
	
        "en_auto_reset":	true,
	"auto_reset_max_velocity":	20,
	"auto_reset_max_v_cov_instant":	0.20000000298023224,
	"auto_reset_max_v_cov":	0.20000000298023224,
	"auto_reset_max_v_cov_timeout_s":	0.5,
	"auto_reset_min_features":	1,
	"auto_reset_min_feature_timeout_s":	10,
	"ok_state_grace_timeout_s":	2,
	"auto_fallback_timeout_s":	3,
	"auto_fallback_min_v":	0.600000023841858,
	"en_cont_yaw_checks":	false,
	"fast_yaw_thresh":	5,
	"fast_yaw_timeout_s":	1.75,
	"anchor_cone_h_deg":	32.5,
	"anchor_cone_v_deg":	32.5,
	"yaml_folder":	"/usr/share/modalai/voxl-open-vins/VoxlConfig/starling2",
	"using_stereo":	0,
	"takeoff_alt_threshold":	0.5,
	"takeoff_occlude_stereo_left":	false,
	"takeoff_occlude_stereo_right":	false,
	"sync_config":	true,
	"fusion_rate_dt_ms":	20,
	"imu_body_frame_mode":	true,
	"quality_low_thresh_initial":	15,
	"quality_low_thresh_good":	14,
	"quality_high_thresh":	35,
	"quality_initial_to_bad_count":	20,
	"quality_initial_to_good_count":	50,
	"quality_bad_to_good_count":	60,
	"quality_good_to_bad_count":	45
}
