/**
 * This file contains configuration that's specific to voxl-uvc-server.
 * parameter descriptions:
 * 
 * width: Desired image width. (e.g. 640)
 * Default is 640.
 *
 * height: Desired image height. (e.g. 480)
 * Default is 480.
 *
 * height: Desired frame rate in fps (e.g. 15).
 * Default is 30.
 *
 * pipe-name: Desired MPA pipe name in /run/mpa (e.g. webcam).
 * Default is uvc.
 *
 */
{
	"pipe_name":	"uvc",
	"width":	640,
	"height":	512,
	"fps":	60
}
